services:
  keycloak:
    image: "quay.io/keycloak/keycloak:25.0.2"
    command:
      - start-dev
      - --health-enabled=true
      - --import-realm
    volumes:
      - ./keycloak:/opt/keycloak/data
      - ./PowerRanger.json:/opt/keycloak/data/import/PowerRanger.json
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    #      KEYCLOAK_IMPORT: ./PowerRanger.json
    ports:
      - '8080:8080'

  mysql:
    image: mysql:8.4.0
    restart: always
    environment:
      MYSQL_DATABASE: 'simple_go_db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'yuji'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'yuji'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'yuji'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - keycloak:/var/lib/mysql
volumes:
  keycloak: